FROM node:16-alpine as builder

ARG ENVIRONMENT
ARG LOG_LEVEL
ARG BASE_URL
ARG HTTP_HOST
ARG HTTP_PORT
ARG JWT_SECRET_ACCESS
ARG JWT_EXPIRE_ACCESS
ARG JWT_SECRET_REFRESH
ARG JWT_EXPIRE_REFRESH

# Telegram
ARG BOT_TOKEN
ARG BOT_CHAT_ID

# Mongo
ARG MONGODB_URL
ARG MONGODB_DATABASE_NAME

# Redis
ARG REDIS_PASSWORD
ARG REDIS_URL

WORKDIR /usr/app

RUN apk update

COPY . .

# Install app dependencies adn buil
RUN yarn install --frozen-lockfile && yarn build

# Install app dependencies adn buil
RUN yarn seed:all

FROM node:16-alpine as production
WORKDIR /usr/src

COPY --from=builder /usr/app/node_modules ./node_modules
COPY --from=builder /usr/app/dist ./dist

CMD [ "node", "./dist/index.js" ]
